//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition_Detail
    {
        public int ID_Competition_Detail { get; set; }
        public Nullable<int> ID_Competition { get; set; }
        public Nullable<int> ID_Combattant { get; set; }
        public Nullable<int> ID_Categorie { get; set; }
        public Nullable<int> ID_Combat { get; set; }
        public Nullable<int> ID_Poule { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Combat Combat { get; set; }
        public virtual Combattant Combattant { get; set; }
        public virtual Competition Competition { get; set; }
        public virtual Poule Poule { get; set; }
    }
}
