//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Competition()
        {
            this.Competition_Detail = new HashSet<Competition_Detail>();
        }
    
        public int ID_Competition { get; set; }
        public string Nom_Competition { get; set; }
        public string Lieu_Competition { get; set; }
        public Nullable<System.DateTime> Date_Competition { get; set; }
        public byte[] FondScoreboard_Competition { get; set; }
        public byte[] Logo_Competition { get; set; }
        public string LieuPese_Competition { get; set; }
        public Nullable<System.DateTime> Date_Pese { get; set; }
        public string Condition_Pese { get; set; }
        public Nullable<int> DroitCombattant { get; set; }
        public Nullable<int> Remboursement { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Competition_Detail> Competition_Detail { get; set; }
    }
}
