//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Competition_JJBEntities : DbContext
    {
        public Competition_JJBEntities()
            : base("name=Competition_JJBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Combat> Combats { get; set; }
        public virtual DbSet<Combattant> Combattants { get; set; }
        public virtual DbSet<Competition_Detail> Competition_Detail { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<Poule> Poules { get; set; }
    }
}
